import test from 'node:test';
import assert from 'node:assert/strict';
import { randomUUID } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { mkdtempSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { PNG } from 'pngjs';
import { createApp } from '../server/app.js';
import { createImageWorkflow, imageDay, IMAGE_PROJECT } from '../server/image-workflow.js';
import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StreamableHTTPClientTransport } from '@modelcontextprotocol/sdk/client/streamableHttp.js';

const png = new PNG({ width: 32, height: 32 }); png.data.fill(100);
const image = 'data:image/png;base64,' + PNG.sync.write(png).toString('base64');
const conversation = () => ({ projectUrl: IMAGE_PROJECT.url, conversationUrl: 'https://chatgpt.com/c/' + randomUUID() });
const setup = async (t, options = {}) => {
  const app = createApp({ dbPath: ':memory:', ...options });
  await new Promise(r => app.server.listen(0, '127.0.0.1', r));
  t.after(async () => { app.server.closeAllConnections(); await new Promise(r => app.server.close(r)); app.db.close(); });
  const origin = `http://127.0.0.1:${app.server.address().port}`;
  const client = role => { let cookie = ''; return async (path, body) => { const response = await fetch(origin + '/api/' + role + path, { method: body ? 'POST' : 'GET', headers: { Origin: origin, Cookie: cookie, 'Content-Type': 'application/json' }, body: body ? JSON.stringify(body) : undefined }); if (response.headers.get('set-cookie')) cookie = response.headers.get('set-cookie').split(';')[0]; return { status: response.status, data: response.headers.get('content-type')?.includes('json') ? await response.json() : Buffer.from(await response.arrayBuffer()) }; }; };
  const teacher = client('teacher'); await teacher('/register', { username: 'teach' + randomUUID().slice(0, 8), name: '老师', password: 'password123', role: 'teacher' });
  const room = (await teacher('/classrooms', { name: '生图课堂', capacity: 15, background: '教室' })).data.classroom;
  const student = client('student'); const user = (await student('/enter-classroom', { name: '同学', code: room.code })).data.user;
  const payload = (kind = 'identity') => ({ requestId: randomUUID(), classId: room.id, kind, photo: image, ...(kind === 'work' ? { workId: randomUUID(), workName: '杯子' } : {}) });
  return { ...app, origin, client, student, teacher, room, user, payload };
};

test('guest exclusion, atomic daily allowance, idempotence and private reference access', async t => {
  const { student, teacher, client, room, payload, db } = await setup(t);
  assert.equal((await student('/image-status')).data.registered, false);
  assert.equal((await student('/image-jobs', payload())).status, 403);
  assert.equal((await student('/image-profile/register', {})).data.registered, true);
  assert.equal((await student('/image-jobs', { ...payload(), photo: 'bad' })).status, 400);
  const a = payload(), b = payload();
  const requests = await Promise.all([student('/image-jobs', a), student('/image-jobs', b)]);
  assert.deepEqual(requests.map(r => r.status).sort(), [201, 429]);
  const accepted = requests[0].status === 201 ? a : b;
  assert.equal((await student('/image-jobs', accepted)).status, 201);
  assert.equal((await student('/image-jobs', { ...accepted, kind: 'work', workId: randomUUID(), workName: 'changed' })).status, 409);
  assert.equal((await student('/image-jobs/' + accepted.requestId + '/photo')).status, 403);
  assert.equal((await teacher('/image-jobs/' + accepted.requestId + '/photo')).status, 200);
  const other = client('student'); await other('/enter-classroom', { name: '另一个', code: room.code });
  assert.equal((await other('/image-jobs/' + accepted.requestId + '/result')).status, 403);
  const otherTeacher = client('teacher'); await otherTeacher('/register', { username: 'otherteacher', name: '其他老师', password: 'password123', role: 'teacher' });
  assert.equal((await otherTeacher('/image-jobs')).data.jobs.length, 0);
  assert.equal((await otherTeacher('/image-jobs/' + accepted.requestId + '/context')).status, 403);
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM image_jobs').get().n, 1);
});

test('fixed identity and work share Beijing calendar quota; late returns never deliver two images a day', async t => {
  let now = Date.parse('2026-10-10T15:59:59Z');
  assert.equal(imageDay(now), '2026-10-10'); assert.equal(imageDay(now + 1000), '2026-10-11');
  const { student, teacher, payload, db } = await setup(t, { imageNow: () => now });
  await student('/image-profile/register', {});
  assert.equal((await student('/image-jobs', payload('work'))).status, 409);
  const identity = payload(); await student('/image-jobs', identity);
  assert.equal((await teacher('/image-jobs/' + identity.requestId + '/complete', { image })).status, 409, 'Require a student conversation before delivery');
  const binding = conversation();
  assert.equal((await teacher('/image-jobs/' + identity.requestId + '/conversation', binding)).status, 200);
  assert.equal((await teacher('/image-jobs/' + identity.requestId + '/complete', { image })).status, 200);
  assert.equal((await student('/image-profile/avatar')).status, 200);
  assert.equal((await student('/image-jobs', payload('work'))).status, 429);
  assert.equal((await teacher('/image-jobs/' + identity.requestId + '/complete', { image })).status, 200);
  assert.equal(db.prepare('SELECT photo,reference FROM image_jobs').get().photo, null);
  now += 1000;
  assert.equal((await student('/image-jobs', payload())).status, 409, 'Fixed identity cannot be replaced');
  const work = payload('work'); assert.equal((await student('/image-jobs', work)).status, 201);
  const context = (await teacher('/image-jobs/' + work.requestId + '/context')).data;
  assert.equal(context.images.length, 2); assert.match(context.prompt, /preserve its face/);
  assert.equal(context.conversationUrl, binding.conversationUrl, 'Work images reuse the fixed identity conversation');
  assert.equal(context.project.url, IMAGE_PROJECT.url);
  const claimId = randomUUID(); assert.equal((await teacher('/image-jobs/' + work.requestId + '/claim', { claimId })).status, 200);
  assert.equal((await teacher('/image-jobs/' + work.requestId + '/claim', { claimId })).data.job.repeated, true);
  assert.equal((await teacher('/image-jobs/' + work.requestId + '/claim', { claimId: randomUUID() })).status, 409);
  assert.equal((await teacher('/image-jobs/' + work.requestId + '/complete', { image, claimId: randomUUID() })).status, 409);
  now += 86400000;
  assert.equal((await student('/image-jobs', payload('work'))).status, 409, 'An uncompleted request is never re-generated automatically');
  assert.equal((await teacher('/image-jobs/' + work.requestId + '/complete', { image, claimId })).status, 200);
  assert.equal((await student('/image-jobs', payload('work'))).status, 429, 'Delivery today consumes today too');
  assert.equal((await student('/image-jobs/' + work.requestId + '/result')).status, 200);
});

test('queue, profile and quota survive restart; rejection retains quota and removes source photos', async t => {
  const directory = mkdtempSync(join(tmpdir(), 'image-queue-')); t.after(() => rmSync(directory, { recursive: true, force: true }));
  const { student, teacher, user, payload, db } = await setup(t, { dbPath: join(directory, 'queue.sqlite') });
  await student('/image-profile/register', {}); const request = payload(); await student('/image-jobs', request);
  const reopened = new DatabaseSync(join(directory, 'queue.sqlite')); t.after(() => reopened.close());
  const workflow = createImageWorkflow(reopened);
  assert.equal(workflow.status(user).remaining, 0); assert.equal(workflow.list(user)[0].id, request.requestId);
  await teacher('/image-jobs/' + request.requestId + '/reject', {});
  assert.equal(workflow.status(user).remaining, 0); assert.equal(db.prepare('SELECT photo FROM image_jobs').get().photo, null);
});

test('official MCP client can list, claim, read images and return a result; tokens rotate and expire', async t => {
  let now = Date.now(); const { student, teacher, payload, origin } = await setup(t, { imageNow: () => now });
  await student('/image-profile/register', {}); const request = payload(); await student('/image-jobs', request);
  assert.equal((await fetch(origin + '/mcp/images')).status, 401);
  assert.equal((await student('/image-mcp-token', {})).status, 403);
  const { token } = (await teacher('/image-mcp-token', {})).data;
  const mcp = new Client({ name: 'workflow-test', version: '1' });
  const transport = new StreamableHTTPClientTransport(new URL(origin + '/mcp/images'), { requestInit: { headers: { Authorization: 'Bearer ' + token } } });
  await mcp.connect(transport); t.after(() => mcp.close());
  assert.equal((await mcp.listTools()).tools.length, 5);
  assert.equal((await mcp.callTool({ name: 'list_image_requests', arguments: {} })).structuredContent.jobs[0].id, request.requestId);
  const claimId = randomUUID(); assert.equal((await mcp.callTool({ name: 'claim_image_request', arguments: { jobId: request.requestId, claimId } })).structuredContent.repeated, false);
  const materials = await mcp.callTool({ name: 'get_image_request', arguments: { jobId: request.requestId } });
  assert.equal(materials.content[1].type, 'image'); assert.ok(!JSON.stringify(materials).includes(token));
  assert.equal(materials.structuredContent.project.url, IMAGE_PROJECT.url);
  assert.equal((await mcp.callTool({ name: 'bind_student_conversation', arguments: { jobId: request.requestId, ...conversation() } })).isError, undefined);
  const delivered = await mcp.callTool({ name: 'return_generated_image', arguments: { jobId: request.requestId, claimId, image } });
  assert.equal(delivered.structuredContent.job.status, 'completed');
  const newer = (await teacher('/image-mcp-token', {})).data;
  assert.equal((await fetch(origin + '/mcp/images', { headers: { Authorization: 'Bearer ' + token } })).status, 401);
  now += 86400001;
  assert.equal((await fetch(origin + '/mcp/images', { headers: { Authorization: 'Bearer ' + newer.token } })).status, 401);
});

test('one persistent conversation per student, distinct same-name accounts, scoped metadata and safe URLs', async t => {
  const { student, teacher, client, room, payload, db } = await setup(t);
  await student('/image-profile/register', {}); const first = payload(); await student('/image-jobs', first);
  const binding = conversation(), path = '/image-jobs/' + first.requestId + '/conversation';
  assert.equal((await student(path, binding)).status, 403);
  assert.equal((await teacher(path, { ...binding, projectUrl: 'https://chatgpt.com/' })).status, 400);
  for (const conversationUrl of ['https://example.com/c/' + randomUUID(), 'https://chatgpt.com/', binding.conversationUrl + '?token=secret', 'https://chatgpt.com/g/g-p-other/c/' + randomUUID(), 'https://user@chatgpt.com/c/' + randomUUID()]) assert.equal((await teacher(path, { ...binding, conversationUrl })).status, 400);
  assert.equal((await teacher(path, binding)).status, 200);
  assert.equal((await teacher(path, binding)).status, 200);
  assert.equal((await teacher(path, conversation())).status, 409, 'Existing conversation is never overwritten');
  const other = client('student'); await other('/enter-classroom', { name: '同学', code: room.code }); await other('/image-profile/register', {});
  const second = payload(); await other('/image-jobs', second);
  assert.equal((await teacher('/image-jobs/' + second.requestId + '/conversation', binding)).status, 409, 'Cannot share another student conversation');
  assert.equal((await teacher('/image-jobs/' + second.requestId + '/conversation', conversation())).status, 200);
  const jobs = (await teacher('/image-jobs')).data.jobs;
  assert.equal(jobs[0].studentName, jobs[1].studentName); assert.notEqual(jobs[0].conversationTitle, jobs[1].conversationTitle);
  assert.notEqual(jobs[0].conversationUrl, jobs[1].conversationUrl);
  const visible = (await student('/image-jobs')).data.jobs[0];
  assert.equal(visible.project, undefined); assert.equal(visible.conversationUrl, undefined);
  const reopenedWorkflow = createImageWorkflow(db);
  assert.equal(reopenedWorkflow.context(db.prepare("SELECT * FROM users WHERE role='teacher'").get(), first.requestId).conversationUrl, binding.conversationUrl);
});
